### ISSUE TITLE
Issue with parallel toolbox on Matlab 2019a - transparency violation error pop_eegfiltnew line 232

### ISSUE THREAD

**Issue by arnodelorme** [widmann/firfilt#1]
System information: 
MATLAB Version: 9.6.0.1072779 (R2019a)
Operating System: Microsoft Windows 10 Work Station Version 10.0 (Build 17134)
Java Version: Java 1.8.0_181-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
Parallel Computing Toolbox                            Version 7.0         (R2019a)
EEGLAB v14.1.2

**Comment by widmann** [comment]
Any instructions how to replicate the problem? Currently I do not have access to R2019a on Windows. Replicable with other architecture or R2018b?

In 14.1.2b line 232 was formatting of the history string. You changed this code in the meantime (commit deb7b081308a1a1ef94184087bceab38ce68ba8c). Please first test with your recent version.

**Comment by arnodelorme** [comment]
I have tried with 2018b and there is no bug. First load the tutorial dataset, then copy it and run pop_eegfiltnew on it. @nucleuscub (Ramon), do you have 2019a available to try?

```
EEG = pop_loadset('filename','eeglab_data.set','filepath','/data/matlab/eeglab/sample_data/');
ALLEEG(2:4) = ALLEEG(1);
parfor i=1:4, ALLEEGNEW(i) = pop_eegfiltnew(ALLEEG(i), 'locutoff',1,'plotfreqz',0); end
```

**Comment by widmann** [comment]
No problem with R2019a on Mac with this code. Neither with pre deb7b08 Version nor with recent version. I do not have R2019a for Windows available.

**Comment by widmann** [comment]
Code also runs flawlessly on R2019a in Linux.

**Comment by widmann** [comment]
No instructions for replication. Closed as invalid.
