### ISSUE TITLE
error pop_eegfiltnew

### ISSUE THREAD

**Issue by guoyongjian111** [widmann/firfilt#12]
![image](https://user-images.githubusercontent.com/82032571/192273179-9d34cf54-1112-4f26-a672-29e01de8f8a4.png)
![image](https://user-images.githubusercontent.com/82032571/192273353-730d7f98-cf82-4a32-96ff-934aa235d689.png)
![image](https://user-images.githubusercontent.com/82032571/192273558-8c6bddbe-2a9d-4762-93e1-0dc0a75626ab.png)

I encountered this error when I was filtering，please help me！thanks

**Comment by widmann** [comment]
Information is not sufficient for debugging. Access to an affected dataset is required. EEGLAB version? Firfilt version?

Best,
Andreas

**Comment by guoyongjian111** [comment]
eeglab is the latest version,firfilt2.6
this is my data https://drive.google.com/file/d/1VYrVqncTI7lL2xDpJdT1VPLBr1rwOvUJ/view?usp=sharing

**Comment by guoyongjian111** [comment]
Sorry. The link is incorrect. The correct link is this one https://drive.google.com/file/d/1B0GuG9jUa5DUMNUL7IdCDhW1f2P5bl8J/view?usp=sharing

**Comment by widmann** [comment]
In your dataset, there are (lot's of) boundary events with event latencies longer than the available data range ([EEG.event.latency] > size(EEG.data,2)). This is invalid. Easiest is to fix on command line with eeg_checkset (including the eventconsistency option).

```
EEG = eeg_checkset(EEG, 'eventconsistency')
[ALLEEG EEG CURRENTSET] = pop_newset( ALLEEG, EEG, CURRENTSET )
eeglab redraw
```

Best,
Andreas

**Comment by guoyongjian111** [comment]
Thank you, I would like to ask how to delete Boundry, because Boundry is because I wrote the preprocessing script, using ASR for artifact removal

**Comment by guoyongjian111** [comment]
I don't need Event for my resting-state EEG data

**Comment by widmann** [comment]
For example using eeg_checkset as suggested in the example code in ma previous message.

**Comment by guoyongjian111** [comment]
I've tried. It doesn't seem to work

**Comment by widmann** [comment]
Try eeg_store instead of pop_newset if this better fits into your pipeline. For example

```
EEG = eeg_checkset(EEG, 'eventconsistency')
[ALLEEG EEG CURRENTSET] = eeg_store(ALLEEG, EEG, CURRENTSET);
eeglab redraw
```

Otherwise, as this is an issue not actually related to firfilt I hope for your understanding that I cannot give further support on this issue. Try posting on EEGLAB mailing list:
https://eeglab.org/others/EEGLAB_mailing_lists.html

Best,
Andreas

**Comment by guoyongjian111** [comment]
Thank you for your generous help！
