### ISSUE TITLE
Potential conflict with signal processing toolbox

### ISSUE THREAD

**Issue by arnodelorme** [widmann/firfilt#9]
We might want to move this function to a private folder?

/System/Volumes/Data/data/matlab/eeglab/plugins/firfilt/firgauss.m and /Applications/MATLAB_R2021b.app/toolbox/signal/signal/firgauss.m

**Comment by widmann** [comment]
```
>> help firgauss
 firgauss FIR Gaussian digital filter design.
    firgauss has been replaced by GAUSSDESIGN.  firgauss still works but
    may be removed in the future. Use GAUSSDESIGN instead. Type help
    GAUSSDESIGN for details.
```

Thus, change really necessary? Is this the way it is generally handeled in EEGLAB?

**Comment by arnodelorme** [comment]
Yes, no other EEGLAB function overloads a MATLAB function. I think the problem will only bother 1% of users and less but could lead to some hard-to-debug issues (which will take time to identify).
